---
- name: Playbook to create user, group and asssigning user into a group
  hosts: web
  tasks:
    - name: Create a Group called dba
      group:
        name: dba
        state: present

    - name: Create a user and assign the user in dba group
      user:
        name: reshmi
        state: present
        groups: dba
